#!/usr/bin/env node
// Combines sections/*.html into sections/data.js
// Run: node build.js

const fs = require('fs');
const path = require('path');

const cats = [
  'javascript', 'typescript', 'browser', 'web-apis', 'rxjs', 'angular',
  'state-management', 'oop-architecture', 'testing',
  'infrastructure', 'graphics', 'nodejs', 'nestjs', 'graphql',
];

const entries = cats.map(id => {
  const html = fs.readFileSync(path.join('sections', `${id}.html`), 'utf8');
  const escaped = html.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$\{/g, '\\${');
  return `  ${JSON.stringify(id)}:\`${escaped}\``;
});

const output = `// Generated by build.js — do not edit directly\nwindow.__S={\n${entries.join(',\n')}\n};\n`;
fs.writeFileSync(path.join('sections', 'data.js'), output);
console.log('sections/data.js updated');
