#!/usr/bin/env node
// Combines sections/*.html into sections/data.js
// Supports two locales: en (sections/*.html) and uk (sections/uk/*.html, falls back to en)
// Run: node build.js

const fs = require('fs');
const path = require('path');

const cats = [
  'javascript', 'typescript', 'browser', 'web-apis', 'rxjs', 'angular',
  'state-management', 'oop-architecture', 'testing',
  'infrastructure', 'graphics', 'nodejs', 'nestjs', 'graphql', 'electron', 'webrtc',
  'csharp', 'sql',
];

function escape(html) {
  return html.replaceAll('\\', '\\\\').replaceAll('`', '\\`').replaceAll('${', '\\${');
}

function readSection(id, locale) {
  const ukPath = path.join('sections', 'uk', `${id}.html`);
  const enPath = path.join('sections', `${id}.html`);
  if (locale === 'uk' && fs.existsSync(ukPath)) {
    return fs.readFileSync(ukPath, 'utf8');
  }
  return fs.readFileSync(enPath, 'utf8');
}

function buildLocale(locale) {
  return cats.map(id => {
    const html = readSection(id, locale);
    return `  ${JSON.stringify(id)}:\`${escape(html)}\``;
  });
}

const enEntries = buildLocale('en');
const ukEntries = buildLocale('uk');

const output = [
  '// Generated by build.js — do not edit directly',
  `window.__S_en={\n${enEntries.join(',\n')}\n};`,
  `window.__S_uk={\n${ukEntries.join(',\n')}\n};`,
  '// Default alias — overridden at runtime by app.js based on localStorage',
  'window.__S=window.__S_en;',
  '',
].join('\n');

fs.writeFileSync(path.join('sections', 'data.js'), output);
console.log('sections/data.js updated (en + uk)');
